### ISSUE TITLE
TK03 - (US07) - Crear detalles de Preguntas Frecuentes

### ISSUE THREAD

**Issue by jmsanchezfin** [AndreaReyna/ISPC-Fullstack#52]
Asociado a #49 

Detalles en el footer

**Comment by FrancoTrivini** [comment]
Cree una carpeta en el Footer para crear las FAQs

**Comment by jmsanchezfin** [comment]
@FrancoTrivini esta el modulo help-center, componente help en la rama feature_help para levantar de una sola ves todo lo relacionado a ayuda
el ejemplo es este https://www.cuspide.com/centrodeayuda
