### ISSUE TITLE
Error en http://localhost:4200/user

### ISSUE THREAD

**Issue by jmsanchezfin** [AndreaReyna/ISPC-Fullstack#79]
Error en el link de user, por mas que no este logeado me lleva a la page como si lo estuviera. Hay q hacer una aparte para los que no estan logeados, o que nos lleve a registro en todo caso, como estaba antes. Revisar eso.

**Comment by AndreaReyna** [comment]
Sigue apareciendo el boton de login/registro a la derecha, la idea es que ese boton cambie por login/registro segun corresponda y que mi cuenta aparezca solo cuando este logeado, pero como no tenemos login lo deje asi para que se vea, sino no ibamos a ver esa seccion hasta que no tengamos la posibilidad de logear. con Admin es lo mismo, luego hay que ocultarlo
